### ISSUE TITLE
Bugs to fix

### ISSUE THREAD

**Issue by ckcherry23** [PulsePace/PulsePace#21]
## Todo:
- [ ]  Fix music from designer playing in game view - Façade for audio manager(?)
- [ ]  Add step for audio player = 0.25
- [x]  Trim song until offset for gameplay (seems like the hit objects appear earlier than expected)
Correction: seems like hit objects appear right after one another
- [ ]  #17 
- [ ]  Fix slider last tap bug
- [x] Add default level in gameplay or disable 'play' button on menu
- [ ] #20
